## Conda Environment file
name: course
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python<=3.11
  - pytorch<2.0
  - pytorch-cuda==11.7
  - pycocotools>=2.0.6
  - timm>=0.6.12
  - pip
  - pandas
  - wandb
  - torchvision
  - scikit-image
  - scikit-learn
  - matplotlib
  - pip:
    - fastprogress
    - torcheval
